import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  allSidebar: [{ type: 'autogenerated', dirName: '.' }],
  backendSidebar: [{ type: 'autogenerated', dirName: 'development/backend' }],
  frontendSidebar: [{ type: 'autogenerated', dirName: 'development/frontend' }],
  cloudSidebar: [{ type: 'autogenerated', dirName: 'development/cloud' }],
  aiSidebar: [{ type: 'autogenerated', dirName: 'ai-data/ai' }],
  dataSidebar: [{ type: 'autogenerated', dirName: 'ai-data/data' }],
  englishSidebar: [{ type: 'autogenerated', dirName: 'language/english' }],
  japaneseSidebar: [{ type: 'autogenerated', dirName: 'language/japanese' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
